
[env]

[font]
normal = { family="CaskaydiaCove Nerd Font Mono" }
size = 11.5

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [{ key="N", mods="Control | Shift", action="SpawnNewInstance" },]

[general]
import = ["~/.config/alacritty/themes/themes/tokyo_night.toml"]
