
[env]

[font]
normal = { family="FiraCode Nerd Font Mono" }
size = 11.25

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [{ key="N", mods="Control | Shift", action="SpawnNewInstance" },]

[window]
blur = true
opacity = 0.82

[general]
import = ["~/.config/alacritty/themes/themes/tokyo_night.toml"]
