# starship.toml
# Managed by Gemini CLI

# Inserts a newline before the prompt.
add_newline = true

# The prompt format. Directory on the first line, prompt character on the second.
format = """$directory$git_branch$git_status$fill$cmd_duration$time\n$character"""
right_format = "$python"

[fill]
symbol = " "

[cmd_duration]
format = "took [$duration](bold yellow) "

[time]
disabled = false
format = "at [$time](#FFA500) "

[directory]


style = "cyan"
repo_root_style = "bold yellow"
fish_style_pwd_dir_length = 1
truncate_to_repo = true

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[python]
format = "via [🐍 $virtualenv](bold green)"