# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = waybar -c ~/.config/hypr/waybar/config.jsonc -s ~/.config/hypr/waybar/style.css

# Auto wallpaper script
exec-once = /home/highonh2o/.config/hypr/scripts/swww-random.sh

exec-once = swaync

exec-once = gnome-keyring-daemon --start --components=secrets,ssh

exec-once = hyprpm reload
