# Hyprland Modular Configuration

# Source all configuration files
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/programs.conf
source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/configs/env_vars.conf
source = ~/.config/hypr/configs/look_and_feel.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/window_rules.conf
source = ~/.config/hypr/configs/plugins.conf
